#!/bin/bash
# blender-add-on

Version=3.6

echo "Blender "$Version

echo "Check your .zip files :-)"

ls Bilder/Blender/Add-ons/

echo "Check your add-ons"

ls ~/.config/blender/$Version/scripts/addons/

while true; do
    read -p "Continue? " yn
    case $yn in
        [Yy]* ) rm -rf ~/.config/blender/$Version/scripts/addons/*;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

unzip ~/Bilder/Blender/Add-ons/\*.zip  -d ~/.config/blender/$Version/scripts/addons/

echo "Done"
